server:
  port: 9001
  servlet:
    context-path: /plus
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lvy?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
mybatis-plus:
  config-location: classpath:mapper/mybatis-config.xml
  type-aliases-package: com.baizhi.entity
